src/components/geolocated.js, tests/__snapshots__/geolocated.test.js.snap, tests/geolocated.test.js
As pointed out by @RishabhJain96 in #14, props aren't passed from the HOC to the child component.
Fixes and closes #15 
Closes #14
=> Add props passing

.travis.yml, CONTRIBUTING.md, README.md, package.json
=> Add semantic-release

docs-resources/DOCS.md, webpack.config.babel.js
Removes `browser-icons` and fixes missing CSS webpack error.
=> Fix errors in demo

tests/typescript/typings.json
Fixes a deprecation warning in the TypeScript typings test runs
=> Update react typings

package.json, webpack.config.babel.js
Updates webpack and related packages to webpack 2 versions
Closes #64
=> Update to webpack 2

package.json, tests/__snapshots__/geolocated.test.js.snap
=> chore(package): update jest to version 19.0.0

package.json, webpack.config.babel.js
=> Depend on prop-types according to docs

package.json
=> chore(package): update babel-jest to version 20.0.2

package.json
=> chore(packages): update webpack and related plugins

package.json
=> chore(package): update react-ghfork to version 0.5.1

.travis.yml, package.json
=> build: upgrade semantic-release and supply a node version needed by it

package.json
=> chore(package): update semantic-release to version 15.1.6

index.d.ts, tests/typescript/index.tsx
=> fix(typings): add missing config options

README.md, demo/App.jsx, index.d.ts, src/components/geolocated.js, tests/typescript/index.tsx, yarn.lock
=> feat: add onError and onSuccess callbacks

package.json, yarn.lock
=> chore(typescript): upgrade TypeScript-related dependencies

yarn.lock
=> chore(packages): upgrade @types/react

.gitignore, index.d.ts
A small TS related improvements
=> fix(typings): add missing field of the HOC config

package.json, tests/typescript/index.tsx, yarn.lock
=> build(deps-dev): upgrade typescript

package.json, yarn.lock
=> build(deps-dev): remove husky dev dependency

.eslintrc.json, .gitignore, .postcssrc.json, demo/App.jsx, demo/App.mdx, demo/Demo.jsx, demo/DemoPage.jsx, demo/index.css, demo/index.html, demo/index.jsx, doczrc.js, package.json, tailwind.config.js, yarn.lock
docz was unnecessarily complex for this repo, move to simple parcel-based app.
=> Get rid of docz

README.md
There was a typo in the readme code making the code invalid.
Fixes #1062
=> fix(readme): fix typo in sample code

.github/workflows/nodejs.yml, .github/workflows/pages.yml
Also, get rid of node cache, it takes more time than it saves.
=> build: fix pages action

.github/workflows/release.yml, package.json
This increases the trustworthiness of the released artifacts.
=> feat: publish with provenance

package-lock.json, package.json, tests/geolocated.test.tsx
Also implement the mocks properly.
=> chore: upgrade typescript to 5.7.2

package-lock.json, package.json
Downgrade typescript, the typescript-eslint is not ready.
=> chore: fix dependency issues

.github/dependabot.yml, package-lock.json, package.json
This pull request includes updates to the `.github/dependabot.yml` and `package.json` files to add new patterns for dependencies and remove an unused package.
Dependency management updates:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R17-R34): Added new patterns for `jest`, `react`, and `testing-library` dependencies to ensure they are tracked and updated by Dependabot.
Package removal:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L67): Removed the unused `@types/react-test-renderer` package.
=> Dependabot group react
